# Generated by Django 4.0.2 on 2022-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientoffer',
            name='user',
        ),
        migrations.AddField(
            model_name='clientoffer',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
