# Generated by Django 4.0.2 on 2022-03-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_clientoffer_user_clientbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
