# Generated by Django 4.0.2 on 2022-03-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_clientbooking_user_alter_clientoffer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='arrival_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
