# Generated by Django 4.0.2 on 2022-03-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_clientbooking_arrival_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetail',
            old_name='first_name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='clientdetail',
            old_name='last_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='clientbooking',
            name='no_of_person',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
