# Generated by Django 4.0.2 on 2022-03-15 03:59

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_rename_first_name_clientdetail_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientoffer',
            name='duration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientoffer',
            name='image',
            field=models.ImageField(null=True, upload_to='offer/'),
        ),
        migrations.AlterField(
            model_name='clientoffer',
            name='trip_desc',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
