# Generated by Django 4.0.2 on 2022-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_clientoffer_duration_clientoffer_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientbooking',
            name='confirmance',
            field=models.CharField(choices=[('confired', 'confirmed'), ('cancled', 'cancled')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='clientbooking',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='clientbooking',
            name='package_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='arrival_date',
            field=models.DateTimeField(null=True),
        ),
    ]
