# Generated by Django 4.0.2 on 2022-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientbooking_confirmance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='clientbooking',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
