# Generated by Django 4.0.2 on 2022-03-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_alter_clientbooking_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='confirmance',
            field=models.CharField(choices=[('confired', 'confirmed'), ('cancled', 'cancled'), ('null', 'null')], default='null', max_length=12),
        ),
    ]
