# Generated by Django 4.0.2 on 2022-03-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_alter_clientbooking_confirmance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientbooking',
            old_name='arrival_date',
            new_name='arraival_date',
        ),
    ]
