# Generated by Django 4.0.2 on 2022-03-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_rename_arrival_date_clientbooking_arraival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientbooking',
            name='confirmance',
            field=models.CharField(choices=[('confirmed', 'confirmed'), ('cancled', 'cancled'), ('null', 'null')], default='null', max_length=12),
        ),
    ]
