# Generated by Django 4.0.2 on 2022-03-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='image',
            field=models.ImageField(null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='slug',
            field=models.SlugField(max_length=1000, null=True),
        ),
    ]
