# Generated by Django 4.0.2 on 2022-03-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblog',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Hand', 'Cash on Hand'), ('esewa', 'esewa'), ('khalti', 'khalti')], default='null', max_length=12),
        ),
    ]
